# Generated by Django 5.2.17 on 2026-09-27 13:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0004_pricehistory"),
        ("tenants", "0005_tenant_first_device_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("shift_id", models.UUIDField()),
                ("bill_no", models.CharField(max_length=9)),
                ("sold_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                ("item_count", models.DecimalField(decimal_places=3, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rounding", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("partially_refunded", "Partially Refunded"),
                            ("refunded", "Refunded"),
                        ],
                        default="paid",
                        max_length=20,
                    ),
                ),
                (
                    "flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("rolled_up_at", models.DateTimeField(blank=True, null=True)),
                ("device_id", models.BigIntegerField(blank=True, null=True)),
                ("app_version", models.CharField(blank=True, default="", max_length=32)),
                ("discount_type", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "discount_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "discount_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("customer_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="tenants.counter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.PositiveIntegerField()),
                ("name_snapshot", models.CharField(max_length=255)),
                ("barcode_snapshot", models.CharField(max_length=64)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cost_snapshot", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sold_at", models.DateTimeField()),
                (
                    "bill",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sales.bill",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("card", "Card"), ("wallet", "Wallet")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tendered",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "change_given",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "bill",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.bill",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["tenant_id", "-sold_at", "id"], name="bill_sold_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["tenant_id", "cashier", "sold_at"], name="bill_cashier_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["tenant_id", "shift_id"], name="bill_shift_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                condition=models.Q(("rolled_up_at__isnull", True)),
                fields=["tenant_id", "received_at"],
                name="bill_rollup_pending_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flags__contains", ["bill_no_conflict"]), _negated=True),
                fields=("tenant_id", "bill_no"),
                name="uniq_bill_tenant_bill_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="billitem",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "bill", "product"), name="uniq_bill_item_product"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tenant_id", "bill"], name="payment_bill_idx"),
        ),
    ]
