# Generated by Django 5.2.17 on 2026-09-27 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
        ("tenants", "0005_tenant_first_device_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeldBill",
            fields=[
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("shift_id", models.UUIDField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("recalled", "Recalled"),
                            ("deleted", "Deleted"),
                            ("abandoned", "Abandoned"),
                        ],
                        max_length=10,
                    ),
                ),
                ("client_updated_at", models.DateTimeField()),
                (
                    "cashier",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="held_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="held_bills",
                        to="tenants.counter",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "counter"], name="held_bill_counter_idx")
                ],
            },
        ),
    ]
