# Generated by Django 5.2.17 on 2026-09-27 17:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_pricehistory"),
        ("sales", "0002_heldbill"),
        ("tenants", "0005_tenant_first_device_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("shift_id", models.UUIDField()),
                ("original_bill_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("expired_damaged", "Expired Damaged"),
                            ("wrong_item", "Wrong Item"),
                            ("changed_mind", "Changed Mind"),
                            ("price_error", "Price Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("restock", models.BooleanField()),
                (
                    "refund_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("card", "Card"), ("wallet", "Wallet")],
                        max_length=10,
                    ),
                ),
                ("paid_from_drawer", models.BooleanField()),
                ("refund_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("returned_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                (
                    "flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("rolled_up_at", models.DateTimeField(blank=True, null=True)),
                ("device_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="tenants.counter",
                    ),
                ),
                (
                    "original_bill",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.bill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "price_source",
                    models.CharField(
                        choices=[("paid", "Paid"), ("current", "Current")], max_length=10
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_refund", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cost_snapshot", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bill_item",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="sales.billitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "return_record",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sales.return",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["tenant_id", "original_bill"], name="return_bill_idx"),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(fields=["tenant_id", "shift_id"], name="return_shift_idx"),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(
                fields=["tenant_id", "cashier", "returned_at"], name="return_cashier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="return",
            index=models.Index(
                condition=models.Q(("rolled_up_at__isnull", True)),
                fields=["tenant_id", "received_at"],
                name="return_rollup_pending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="returnitem",
            index=models.Index(fields=["tenant_id", "bill_item"], name="return_item_bill_item_idx"),
        ),
        migrations.AddIndex(
            model_name="returnitem",
            index=models.Index(fields=["tenant_id", "product"], name="return_item_product_idx"),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "return_record", "product"), name="uniq_return_item_product"
            ),
        ),
    ]
