# Generated by Django 5.2.17 on 2026-09-21 15:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("cashier", "Cashier"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("pin_hash", models.CharField(blank=True, max_length=255, null=True)),
                ("pin_verifier", models.CharField(blank=True, max_length=255, null=True)),
                ("default_counter_id", models.BigIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        models.F("tenant_id"),
                        condition=models.Q(("email__isnull", False)),
                        name="uniq_user_tenant_email_lower",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("username"),
                        models.F("tenant_id"),
                        condition=models.Q(("username__isnull", False)),
                        name="uniq_user_tenant_username_lower",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("full_name"),
                        models.F("tenant_id"),
                        condition=models.Q(("role", "cashier")),
                        name="uniq_user_tenant_cashier_name_lower",
                    ),
                ],
            },
        ),
    ]
