# Generated by Django 5.2.17 on 2026-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinDelay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("counter_id", models.BigIntegerField()),
                ("user_id", models.BigIntegerField()),
                ("fail_count", models.PositiveIntegerField(default=0)),
                ("next_allowed_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "counter_id", "user_id"),
                        name="uniq_pin_delay_counter_user",
                    )
                ],
            },
        ),
    ]
