# Generated by Django 5.2.17 on 2026-09-26 11:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_pindelay"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="uniq_user_tenant_email_lower",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="uniq_user_tenant_username_lower",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="uniq_user_tenant_cashier_name_lower",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.F("tenant_id"),
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email__isnull", False)),
                name="uniq_user_tenant_email_lower",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.F("tenant_id"),
                django.db.models.functions.text.Lower("username"),
                condition=models.Q(("username__isnull", False)),
                name="uniq_user_tenant_username_lower",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.F("tenant_id"),
                django.db.models.functions.text.Lower("full_name"),
                condition=models.Q(("role", "cashier")),
                name="uniq_user_tenant_cashier_name_lower",
            ),
        ),
    ]
