# Generated by Django 5.2.17 on 2026-09-27 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_platform_admin_to_django_admin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PinDelay",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pin_hash",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pin_verifier",
        ),
    ]
