# Generated by Django 5.2.17 on 2026-09-21 15:19

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("store_name", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("logo", models.CharField(blank=True, default="", max_length=255)),
                ("currency", models.CharField(default="PKR", max_length=3)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("prices_include_tax", models.BooleanField(default=False)),
                ("block_when_out_of_stock", models.BooleanField(default=False)),
                ("receipt_paper_mm", models.PositiveSmallIntegerField(default=80)),
                ("receipt_header", models.CharField(blank=True, default="", max_length=255)),
                ("receipt_footer", models.CharField(blank=True, default="", max_length=255)),
                ("receipt_show_barcode", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
