# Generated by Django 5.2.17 on 2026-09-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_devicecode_device"),
    ]

    # Altering the `counter` foreign key makes the schema editor drop every
    # index on `counter_id`, the partial unique one included, without adding it
    # back. Remove it first and add it again last so the database keeps it.
    operations = [
        migrations.RemoveConstraint(
            model_name="device",
            name="uniq_device_live_per_counter",
        ),
        migrations.AlterField(
            model_name="device",
            name="counter",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="tenants.counter",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="token_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="devicecode",
            name="code_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="devicecode",
            name="counter",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="device_codes",
                to="tenants.counter",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["tenant_id", "counter"], name="device_tenant_counter_idx"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("token_hash",), name="uniq_device_token_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicecode",
            constraint=models.UniqueConstraint(fields=("code_hash",), name="uniq_device_code_hash"),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("counter",),
                name="uniq_device_live_per_counter",
            ),
        ),
    ]
