# Generated by Django 5.2.17 on 2026-09-27 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_pricehistory"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("receive", "Receive"),
                            ("adjust_add", "Adjust Add"),
                            ("adjust_remove", "Adjust Remove"),
                            ("count_correction", "Count Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qty_delta", models.DecimalField(decimal_places=3, max_digits=12)),
                ("ref_type", models.CharField(blank=True, default="", max_length=20)),
                ("ref_id", models.CharField(blank=True, default="", max_length=64)),
                ("reason", models.CharField(blank=True, default="", max_length=20)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "product", "-occurred_at"],
                        name="stock_move_product_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("type", "sale")),
                        fields=("tenant_id", "ref_type", "ref_id", "product"),
                        name="uniq_stock_move_sale_ref",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("type", "return")),
                        fields=("tenant_id", "ref_type", "ref_id", "product"),
                        name="uniq_stock_move_return_ref",
                    ),
                ],
            },
        ),
    ]
