# Generated by Django 5.2.17 on 2026-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=50)),
                ("entity_type", models.CharField(blank=True, default="", max_length=50)),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
                ("device_id", models.BigIntegerField(blank=True, null=True)),
                ("client_event_id", models.UUIDField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-occurred_at", "-id"],
                        name="audit_log_tenant_time_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "action", "-occurred_at", "-id"],
                        name="audit_log_tenant_action_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "entity_type", "entity_id"],
                        name="audit_log_entity_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("client_event_id__isnull", False)),
                        fields=("tenant_id", "client_event_id"),
                        name="uniq_audit_log_tenant_client_event_id",
                    )
                ],
            },
        ),
    ]
