# Generated by Django 5.2.17 on 2026-09-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bills", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "items",
                    models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "gross",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cash",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "card",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wallet",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                ("refund_count", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "refund_amount",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "refund_cost_recovered",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                ("local_date", models.DateField()),
            ],
            options={
                "db_table": "sales_daily",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "local_date"), name="uniq_sales_daily"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesDailyCashier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("local_date", models.DateField()),
                ("cashier_id", models.BigIntegerField()),
                ("bills", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "revenue",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                ("refund_count", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "refund_amount",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "db_table": "sales_daily_cashier",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "local_date", "cashier_id"),
                        name="uniq_sales_daily_cashier",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesDailyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("local_date", models.DateField()),
                ("product_id", models.BigIntegerField()),
                (
                    "qty",
                    models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "revenue",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "returns_qty",
                    models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "refund_amount",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "db_table": "sales_daily_product",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "local_date", "product_id"),
                        name="uniq_sales_daily_product",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesHourly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bills", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "items",
                    models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "gross",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cash",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "card",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wallet",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                ("refund_count", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "refund_amount",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "refund_cost_recovered",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
                ("counter_id", models.BigIntegerField()),
                ("hour_start", models.DateTimeField()),
            ],
            options={
                "db_table": "sales_hourly",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "counter_id", "hour_start"), name="uniq_sales_hourly"
                    )
                ],
            },
        ),
    ]
