# Generated by Django 5.2.17 on 2026-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasesDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("local_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "db_table": "purchases_daily",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "local_date"), name="uniq_purchases_daily"
                    )
                ],
            },
        ),
    ]
