# Generated by Django 5.2.17 on 2026-09-26 11:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="uniq_category_tenant_name_lower",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                models.F("tenant_id"),
                django.db.models.functions.text.Lower("name"),
                name="uniq_category_tenant_name_lower",
            ),
        ),
    ]
