# Generated by Django 5.2.17 on 2026-09-26 13:45

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_tenant_first_unique_indexes"),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("barcode", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("name_lc", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "low_stock_alert",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("archived_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant_id", "updated_at", "id"], name="product_sync_idx"),
                    models.Index(fields=["tenant_id", "category"], name="product_category_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name_lc"], name="product_name_trgm_idx", opclasses=["gin_trgm_ops"]
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_archived", False)),
                        fields=("tenant_id", "barcode"),
                        name="uniq_product_live_barcode",
                    )
                ],
            },
        ),
    ]
