# Generated by Django 5.2.17 on 2026-09-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("changed_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("edit", "Edit"), ("import", "Import")],
                        default="edit",
                        max_length=10,
                    ),
                ),
                ("changed_at", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_history",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "product", "-changed_at"],
                        name="price_history_product_idx",
                    )
                ],
            },
        ),
    ]
